import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ow Cafe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>
          Mais que um café,
          <span>Uma Experiência!</span>
        </h1>
        <Link href="cafes">
          <a>Cafés Especiais</a>
        </Link>
        <Link href="gastronomia">
          <a>Gatronomia</a>
        </Link>
      </header>
    </div>
  )
}
