import Head from "next/head";
import Link from "next/link";
import { Header } from "../components/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ow Cafe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
    </>
  );
}
